### ISSUE TITLE
Handling of invoke?

### ISSUE THREAD

**Issue by cmdcolin** [h3poteto/electron-mock-ipc#32]
Hi there,
Thanks for this great library, I was wondering if invoke is implemented? It seems to just resolve a promise and console.log it

Thanks!

**Comment by cmdcolin** [comment]
If I am not conceiving of the problem correctly  e.g. if I should mock invoke/handle differently let me know

**Comment by h3poteto** [comment]
Now it is not implemented, but if you want to use the invoke method, I can implement it. So, please wait to the next version.

**Comment by cmdcolin** [comment]
Super. I was not aware that it that feature was new to electron in general...I found a workaround for now where I just manually patch the invoke function on ipcRenderer to just return the contents i want but it sounds great to get it more properly done!

**Comment by h3poteto** [comment]
I implemented invoke method, please use v0.3.1.
