### ISSUE TITLE
TypeError: electron_mock_ipc_1.default is not a function

### ISSUE THREAD

**Issue by D0miH** [h3poteto/electron-mock-ipc#43]
Hey,

first of all thanks for this awesome library. 
I have a problem when trying to run my tests. I set up everything as written in the readme. However when I run my tests I get the following error:
`TypeError: electron_mock_ipc_1.default is not a function` 
with a reference to the marked line
```
      1 | import createIPCMock from 'electron-mock-ipc';
      2 | 
    > 3 | const mocked = createIPCMock();
        |                             ^
      4 | const ipcMain = mocked.ipcMain;
      5 | const ipcRenderer = mocked.ipcRenderer;
      6 | export { ipcMain, ipcRenderer };
```

I have no idea how I could fix this error. Do you have any idea what could cause this error?

Thanks in advance:)

**Comment by h3poteto** [comment]
I will investigate it. Could you please tell me your node.js version, and typescript version?

**Comment by D0miH** [comment]
Thanks for your fast response. I am using the latest version of `electron-mock-ipc`. My node version is `v12.13.1`. 
To make it a bit easier for you to track down the issue, I created an example repo:
https://github.com/D0miH/electron-mock-ipc-example-repo

**Comment by h3poteto** [comment]
I can reproduce it,

```
    TypeError: electron_mock_ipc_1.default is not a function

      2 | import { IpcRenderer, IpcMain } from 'electron'
      3 |
    > 4 | const mocked = createIPCMock()
        |                             ^
      5 | const ipcMain = mocked.ipcMain as IpcMain
      6 | const ipcRenderer = mocked.ipcRenderer as IpcRenderer
```

This error has occurred after I upgrade `jest` >= 24.6.0.

**Comment by h3poteto** [comment]
I understand the reason. 

In recently `jest` and `ts-jest` I can't replace module `electron` to `electron-mock-ipc` using jest config. So I updated README for jest and I added example for jest, please read README.

**Comment by D0miH** [comment]
Ok. I see. Thank you very much:)
