### ISSUE TITLE
How to trigger icpRenderer.on ?

### ISSUE THREAD

**Issue by dark-matter-matters** [h3poteto/electron-mock-ipc#576]
Hi,
This is a nice module. However I cannot test my `ipcRenderer.on(...)` methods because I can't find a way to trigger them from *ipcMain*.  
The following snippet does not work : 
```ts
import index from "./index";
import { ipcMain } from "../mock/ElectronMock";
import { ipcRenderer } from "electron";

// Bascis test for ElectronMock implementation
describe("index", () => {
  beforeEach(() => {
    ipcRenderer.on("test", () => console.log("Success!"));
  });

  it("should handle once IPC", async () => {
    ipcMain.emit("test", 2);
    const res = await index(); // await from the basic example to be sure to receive the answer
  });
});
```
It seems that `ipcMain.emit()` does not send the event to ipcRenderers even if the event name is the same. Ideally I would call `ipcMain.send()`, but it's not there. On my real Electron code I use `this.win.webContents.send()`, but there is no equivalent on *ipcMain*.  
Is there a workaround using webContents? I don't understand the point of `ipcRenderer.on()` if *ipcMain* cannot send messages asynchronously.

**Comment by h3poteto** [comment]
Please show me `mock/ElectronMock` file?

And, I don't prepare a way to replace `webContents.send()`, so at the moment you can't mock `webContents.send()`.

**Comment by dark-matter-matters** [comment]
Thanks for your quick answer. Here's my ElectronMock file. It is the default example file provided in this repo : 
```ts
import createIPCMock from "electron-mock-ipc";
import { IpcRenderer, IpcMain } from "electron";

const mocked = createIPCMock();
const ipcMain = mocked.ipcMain as IpcMain;
const ipcRenderer = mocked.ipcRenderer as IpcRenderer;

// This is the equivalent of msw for IPC
export { ipcMain, ipcRenderer };
```
I'm not an expert in IPC, but it is my understanding that an *ipcRenderer* can send a message to another *ipcRenderer* using a webContentsId. But I couldn't find a way to retrieve it.  
As a last resort I guess I can implement a `send` method manually by adding it to the mock context, and by modifying my mock `on` listeners to be triggered by my `send` function.

**Comment by h3poteto** [comment]
Do you inject this ElectronMock file as `electron`? For example https://github.com/h3poteto/electron-mock-ipc/blob/f414c8eee26d1c017a121c7c078358c8784cd8af/example/jest/package.json#L15-L17

**Comment by dark-matter-matters** [comment]
Yes it is injected, and if I remove this line my other ivoke/handle tests are not working. My problem is only with sending messages from *ipcMain* to *ipcRenderer* listeners.  
What is the purpose of `ipcMain.emit` (as it does not triggered *ipcRenderer.on* listeners) ?

**Comment by h3poteto** [comment]
Oh, I see. `ipcMain.emit` is not implemented correctly: https://github.com/h3poteto/electron-mock-ipc/blob/f414c8eee26d1c017a121c7c078358c8784cd8af/src/ipc-main.ts#L95
As you say, `ipcMain.emit` does not send to ipcRenderer.

**Comment by dark-matter-matters** [comment]
Am I not using the lib correctly? Is there a way to override the method to make it work as expected, perhaps with *node* as suggested in this portion of code? 
https://github.com/h3poteto/electron-mock-ipc/blob/f414c8eee26d1c017a121c7c078358c8784cd8af/src/ipc-main.ts#L69-L72

**Comment by h3poteto** [comment]
I think you need to use `ipcMain.send` instead of `ipcMain.emit`. Why did you use `ipcMain.emit`?

**Comment by dark-matter-matters** [comment]
Well I tried. But it does not exist : 

> Property 'send' does not exist on type 'IpcMain'.ts(2339)   

Then, as I explained [above](https://github.com/h3poteto/electron-mock-ipc/issues/576#issuecomment-1111898005), I tried to call it anyways, but nothing happens : 
```ts
(ipcMain as any).send("ConnectionStatus", ConnectionStatus.CONNECTED); // no error, function exists
```

**Comment by h3poteto** [comment]
> Property 'send' does not exist on type 'IpcMain'.ts(2339)

What?
What version of Electron are you using?

**Comment by h3poteto** [comment]
Oh, I misunderstood, we can't call `ipcMain.send`.
https://www.electronjs.org/docs/latest/api/ipc-main#sending-messages
In the first place, this library did not test sending events unilaterally from ipcMain to ipcRenderer.

Hmm...I think I need to implement some functions for `webContents.send` to send events from main to renderer.

**Comment by dark-matter-matters** [comment]
Ok thanks for your answers. I'll do without it for the moment.
