### ISSUE TITLE
Can it run on a browser?

### ISSUE THREAD

**Issue by junjielyu13** [h3poteto/electron-mock-ipc#758]
I have a question. I want to start the electron program on the backend and then start a local web service. Can this web service use this library to communicate with the electron program through IPC?

**Comment by h3poteto** [comment]
This is a mock library. Of course, you can use it on your web service, but this can't communicate with the backed service. What is your purpose?

**Comment by junjielyu13** [comment]
I want electron to open a web server, this web can use IPC to communicate with electron. But I ended up using https for communication.

thank you for your reply.
